"""Initial schema.

Revision ID: 22dccbb6b0a5
Revises: 
Create Date: 2026-09-28 21:41:55.546890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22dccbb6b0a5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('gap_warning', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_runs_started_at', 'job_runs', ['started_at'], unique=False)
    op.create_table('lastfm_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=64), nullable=False),
    sa.Column('params_hash', sa.String(length=64), nullable=False),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('method', 'params_hash', name='uq_lastfm_cache_method_params')
    )
    op.create_table('resolutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('normalized_artist', sa.String(length=512), nullable=False),
    sa.Column('normalized_title', sa.String(length=512), nullable=False),
    sa.Column('spotify_track_id', sa.String(length=64), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_artist', 'normalized_title', name='uq_resolutions_artist_title')
    )
    op.create_table('tracks',
    sa.Column('spotify_track_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('primary_artist', sa.String(length=512), nullable=False),
    sa.Column('artist_ids', postgresql.ARRAY(sa.String(length=64)), nullable=False),
    sa.Column('album_name', sa.String(length=512), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('release_date', sa.String(length=32), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('normalized_key', sa.String(length=1024), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('spotify_track_id')
    )
    op.create_index('ix_tracks_normalized_key', 'tracks', ['normalized_key'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spotify_user_id', sa.String(length=64), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('access_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recently_played_cursor', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spotify_user_id', name='uq_users_spotify_user_id')
    )
    op.create_table('play_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('spotify_track_id', sa.String(length=64), nullable=False),
    sa.Column('played_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('context_uri', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['spotify_track_id'], ['tracks.spotify_track_id'], name='fk_play_events_spotify_track_id_tracks'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_play_events_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'spotify_track_id', 'played_at', name='uq_play_events_user_track_played_at')
    )
    op.create_index('ix_play_events_user_track', 'play_events', ['user_id', 'spotify_track_id'], unique=False)
    op.create_table('recommendation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('spotify_playlist_id', sa.String(length=64), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_recommendation_runs_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'week_start', name='uq_recommendation_runs_user_week')
    )
    op.create_table('saved_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('spotify_track_id', sa.String(length=64), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['spotify_track_id'], ['tracks.spotify_track_id'], name='fk_saved_tracks_spotify_track_id_tracks'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_saved_tracks_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'spotify_track_id', name='uq_saved_tracks_user_track')
    )
    op.create_table('recommendation_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('spotify_track_id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('raw_score', sa.Float(), nullable=False),
    sa.Column('normalized_score', sa.Float(), nullable=False),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['recommendation_runs.id'], name='fk_recommendation_items_run_id_recommendation_runs', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spotify_track_id'], ['tracks.spotify_track_id'], name='fk_recommendation_items_spotify_track_id_tracks'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recommendation_items_run_id', 'recommendation_items', ['run_id'], unique=False)
    op.create_index('ix_recommendation_items_spotify_track_id', 'recommendation_items', ['spotify_track_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recommendation_items_spotify_track_id', table_name='recommendation_items')
    op.drop_index('ix_recommendation_items_run_id', table_name='recommendation_items')
    op.drop_table('recommendation_items')
    op.drop_table('saved_tracks')
    op.drop_table('recommendation_runs')
    op.drop_index('ix_play_events_user_track', table_name='play_events')
    op.drop_table('play_events')
    op.drop_table('users')
    op.drop_index('ix_tracks_normalized_key', table_name='tracks')
    op.drop_table('tracks')
    op.drop_table('resolutions')
    op.drop_table('lastfm_cache')
    op.drop_index('ix_job_runs_started_at', table_name='job_runs')
    op.drop_table('job_runs')
    # ### end Alembic commands ###
